export const csharpKeywords = [
  'Write high-quality, maintainable code in both C#/.NET',
  'desarrollar y mantener aplicaciones utilizando C#',
  'seeking a Senior C#/.NET Software Engineer',
  'backend development using  .NET 6.0/C#',
  'Conocimientos básicos de C# y .NET',
  'Developer with .NET/C#',
  'Extensive experience with C# and the .NET ecosystem',
  'creating responsive applications using C#, .NET',
  'experience in Software development using C#',
  'Strong working knowledge of C# and .NET',
  'Strong technical background with C#',
  'Build out web applications using C#',
  'advanced knowledge of C# and .NET',
  'Experience developing in C#',
  'Experiencia sólida en C#',
  'Strong background in C#',
  'Language fluency in C#',
  'Back-end: C#, Java',
  'Proficiency in C#',
  'Desarrollador C#',
  'sólidos en C#',
  'Expert in C#',
  'Integrate C#',
  'using C#',
  '.NET, C#',
  'C# .Net',
  'C#.NET',
  'C# Developer',
  'Senior C# Developer',
  'C#',
].filter(Boolean);
