export const dotnetKeywords = [
  'Write high-quality, maintainable code in both C#/.NET',
  'utilizando el stack de tecnologías de Microsoft .NET',
  'desarrollar y mantener aplicaciones utilizando C#',
  'Experience in developing REST APIs with .NET',
  'Conocimientos en desarrollo backend con .NET',
  'seeking a Senior C#/.NET Software Engineer',
  'Strong working knowledge in .NET Framework',
  'Experiencia en Desarrollo utilizando .NET',
  'year in a full-stack capacity with .Net',
  'años de experiencia con. Net framework',
  'backend development using  .NET 6.0/C#',
  'Conocimientos básicos de C# y .NET',
  'focalizado en el backend con .NET',
  'desarrollo de aplicaciones .Net',
  'experience specializing in .NET',
  'Especialista en Backend (.NET)',
  'Strong proficiency with .NET',
  'Full-Stack Developer (.NET +',
  'years of experience in .NET',
  'Expertise in .NET Framework',
  'years of experience as .NET',
  'Desarrollador Senior .Net',
  'strong experience in .NET',
  'Strong background in .NET',
  'Developer with .NET/C#',
  'Extensive experience with C# and the .NET ecosystem',
  'creating responsive applications using C#, .NET',
  'experience in Software development using C#',
  'Strong working knowledge of C# and .NET',
  'Strong technical background with C#',
  'Build out web applications using C#',
  'advanced knowledge of C# and .NET',
  'utilizando tecnologías .NET',
  'Experience developing in C#',
  'Experiencia sólida en C#',
  'Strong background in C#',
  'Language fluency in C#',
  'Familiarity with .NET',
  'experience with .NET',
  'strong focus on .NET',
  'Senior .NET Engineer',
  'experiencia en .NET',
  'desarrollo con .NET',
  'Proficiency in .NET',
  'Desarrollador .NET',
  'Back-end: C#, Java',
  'Lead .NET Engineer',
  'Desarrollo en .NET',
  'Proficiency in C#',
  'Dotnet Developer',
  'Full Stack .NET',
  'que domine .NET',
  'equipo de .NET',
  '.NET Developer',
  'Developer .NET',
  'Hands on .NET',
  'sólidos en C#',
  'entorno .NET',
  'Expert in C#',
  'Integrate C#',
  'using .NET',
  '.NET Core',
  '.NET, C#',
  'ASP.NET',
  'C# .Net',
  'C#.NET',
].filter(Boolean);
