export const fluentEnglishKeywords = [
  'Excellent communication skills in both verbal and written English',
  'proficiency in English is essential to effectively communicate',
  'excellent written and verbal communication skills in English',
  'Communicate effectively in English, both written and verbal',
  'Strong verbal and written communication skills in English',
  'great communicator in English - both written and spoken',
  'communicate clearly in English, both written and spoken',
  'Strong verbal and written English communication skills',
  'You must be proficient in English (written and spoken)',
  'Strong verbal and written communications in English',
  'Excellent English verbal and written communication',
  'Advanced English Level is required for this role',
  'requires a minimum of a B1 English comprehension',
  'Nivel alto de inglés, tanto hablado como escrito',
  'Strong English verbal and written communication',
  'Nivel de inglés hablado y escrito medio/alto',
  'AI interview from your computer in English',
  'daily communication with English-speaking',
  'English proficiency at B2 level or higher',
  'Advanced level of spoken/written English',
  'Complete fluency in the English language',
  'Inglés fluido tanto escrito como hablado',
  'English language both written and spoken',
  'Proficiency in English (B2 - C1 level)',
  'Bilingual Full Stack Software Engineer',
  'Fluency in written and spoken English',
  'inglés intermedio/alto (Mínimo B2/C1)',
  'Excellent written and verbal English',
  'Web Development questions in English',
  'advanced written and spoken English',
  'fluent speaking and writing English',
  'Upper-Intermediate level of English',
  'English proficiency: B2 and higher',
  'English proficiency at a B2+ level',
  'English proficiency at B2 C1 level',
  'requiere un nivel de ingles B2/C1',
  'Fluent written and verbal English',
  'tener competencia Alta en Inglès',
  'English level Upper-Intermediate',
  'communicate fluently in English',
  'ingles conversacional mínimo B2',
  'both written and spoken English',
  'level of English is advanced C1',
  'C1+ / English Bilingual Skills',
  'High-level English proficiency',
  'Strong proficiency in English',
  'Strong English communication',
  'Good English language skills',
  'English fluency Skills ONLY',
  'Dominio avanzado del inglés',
  'imprescindible ser bilingüe',
  'English fluency is required',
  'spoken and written English',
  'English level B2 and above',
  'English level B2 or higher',
  'advanced level of English',
  'nivel de inglés mínimo B2',
  'Upper English proficiency',
  'Inglés B2 conversacional',
  'English level - C1 or C2',
  'nivel avanzado de inglés',
  'NIVEL ELEVADO EN INGLÉS',
  'Inglés - nivel avanzado',
  'Conversational English',
  'English - Fully fluent',
  'Inglés conversacional',
  'Inglés indispensable',
  'English: C1 Advanced',
  'alto nivel de inglés',
  'Inglés fluido B2 C1',
  'English: C1 Advance',
  'Fluency in English',
  'English (required)',
  'Nivel de inglés B2',
  'C1+ English Level',
  'English: C1 level',
  'B2+ English level',
  'Fluent in English',
  'English: Advance',
  'Advanced English',
  'English level C1',
  'English Advanced',
  'English Speaker',
  'Polish (Fluent)',
  'Inglés Avanzado',
  'Fluent English',
  'english only',
  'Inglés C1',
].filter(Boolean);
