export const javaKeywords = [
  'Strong programming skills in languages such as Java, C#, or similar',
  'desarrollo de aplicaciones utilizando tecnologías Java',
  'Expertise in backend technologies: Java, or .NET Core',
  'Experiencia en desarrollo de más de 3 años con Java',
  'backend utilizando Java y el framework Spring',
  'Experience with Scala (or Java, Ruby, or C#)',
  'experiencia en programación en lenguaje Java',
  'Develop and mantain Java-based applications',
  'High level programming languages: Java, C#',
  'Java (JEE) technologies: Java Core, Spring',
  'desarrollar soluciones backend con java',
  'Lenguajes de programación (Spring, Java',
  'Extensive experience working with Java',
  'experience with the Java Standard API',
  'Experiencia mínima de 5 años en Java',
  'required developments over our Java',
  'años reales como programador/a Java',
  'Java (Core and advanced concepts)',
  'Java programming at senior level',
  'utilizando Java para el backend',
  'implement solutions using Java',
  'Experto en Java 1.8 y superior',
  'Familiarity with Java, Spring',
  'Dominio del ecosistema Spring',
  'Sólidos conocimientos en Java',
  'Desarrollador FullStack Java',
  'years of experience as Java',
  'Amplia experiencia con Java',
  'years of experience in Java',
  'Desarrollo JAVA SprintBoot',
  'experiencia sólida en Java',
  'years of Java development',
  'años en Java 7 o superior',
  'Strong expertise in Java',
  'Ecosistema Java y Spring',
  'enfoque especial en Java',
  'Strong knowledge of Java',
  'Solid background in Java',
  'Desarrolladores/as Java',
  'especialmente en Java',
  'proficient with Java',
  'Experience with Java',
  'framework de Spring',
  'proficiency in Java',
  'Desarrollador Java',
  'Spring framework',
  'Dominio de Java',
  'Java Spring',
  'Spring Boot',
  'springboot',
  'Sr. Java',
].filter(Boolean);
