export const javaKeywords = [
  'Strong programming skills in languages such as Java, C#, or similar',
  'desarrollo de aplicaciones utilizando tecnologías Java',
  'Expertise in backend technologies: Java, or .NET Core',
  'Experiencia en desarrollo de más de 3 años con Java',
  'Experience with Scala (or Java, Ruby, or C#)',
  'experiencia en programación en lenguaje Java',
  'experience in software development with Java',
  'server side programming languages like Java',
  'Develop and mantain Java-based applications',
  'Java (JEE) technologies: Java Core, Spring',
  'Experiencia previa en desarrollo en Java',
  'desarrollar soluciones backend con java',
  'Lenguajes de programación (Spring, Java',
  'High level programming languages: Java',
  'Extensive experience working with Java',
  'experience with the Java Standard API',
  'development using the Java ecosystem',
  'Experiencia mínima de 5 años en Java',
  'required developments over our Java',
  'años reales como programador/a Java',
  'Java (Core and advanced concepts)',
  'Java programming at senior level',
  'experience developing with Java',
  'utilizando Java para el backend',
  'implement solutions using Java',
  'Experto en Java 1.8 y superior',
  'Familiarity with Java, Spring',
  'Dominio del ecosistema Spring',
  'Sólidos conocimientos en Java',
  'Desarrollador FullStack Java',
  'years of experience as Java',
  'Amplia experiencia con Java',
  'years of experience in Java',
  'Desarrollo JAVA SprintBoot',
  'experiencia sólida en Java',
  'years of Java development',
  'años en Java 7 o superior',
  'Strong expertise in Java',
  'Ecosistema Java y Spring',
  'enfoque especial en Java',
  'Strong knowledge of Java',
  'Solid background in Java',
  'language preferably Java',
  'Desarrolladores/as Java',
  'languages such as Java',
  'especialmente en Java',
  'proficient with Java',
  'SR Full Stack - Java',
  'Experience with Java',
  'uso del marco Spring',
  'experiencia en java',
  'framework de Spring',
  'proficiency in Java',
  'desarrollador Java',
  'herramientas java',
  'framework Spring',
  'Spring framework',
  'Java Development',
  'Java with Spring',
  'Full Stack Java',
  'Dominio de Java',
  'Senior en Java',
  'Java Developer',
  'Strong in Java',
  'Java Mandatory',
  'Java Spring',
  'Spring Boot',
  'springboot',
  'Spring MVC',
  'Sr. Java',
].filter(Boolean);
