export const pythonKeywords = [
  'years of mastery with development languages (Python',
  'Experiencia mínima de 5 años con Python (Flask)',
  'años de experiencia desarrollando en Python',
  'Desarrollar y mantener features en Python',
  'Backend experience Python FastAPI',
  'Python y PySpark (Indispensables)',
  'Experience with Flask or FastAPI',
  'experience programming in Python',
  'Excellent experience with Python',
  'Senior Fullstack Engineer Python',
  'sólida experiencia con FastApi',
  'Backend: Python, Django/Flask',
  'desarrollo backend con Python',
  'Expertise in Python language',
  'experienca en Python FastAPI',
  'años demostrables con Python',
  'Solid experience with Python',
  'Full Stack Developer Python',
  'Full Stack Engineer Python',
  'Python Software Engineer',
  'Desarrollador de Python',
  'Strong Python expertise',
  'Experiencia con Python',
  'Python, Flask, FastAPI',
  'Proficiency in Python',
  'Desarrollo en Python',
  'experience in Python',
  'Proficient in Python',
  'Strong Python skills',
  'mastery with Python',
  'Python Specialist',
  'Python Developer',
  'Back-end Python',
  'Python y Flask',
  'Senior Python',
].filter(Boolean);
