export const reactKeywords = [
  'Expertise in React and React Native for web and mobile development',
  'experiencia profesional en desarrollo Frontend con React',
  'experience developing Web applications using ReactJS',
  'Experience with React and TypeScript',
  'with a strong proficiency in React',
  'years of proficiency in React',
  'Proven experience with React',
  'with a strong focus on React',
  'specializing in React JS',
  'Senior React Developer',
  'especializado en React',
  'React Native Developer',
  'with a focus on React',
  'React Native Engineer',
  'Experiencia en React',
  'expert-level React',
  'ReactJS (Avanzado)',
  'Senior ReactJS',
  'React Native',
].filter(Boolean);
