export const reactKeywords = [
  'Expertise in React and React Native for web and mobile development',
  'experiencia profesional en desarrollo Frontend con React',
  'experience developing Web applications using ReactJS',
  'front-end development using React.js',
  'Experience with React and TypeScript',
  'experience working with React',
  'alto nivel técnico en ReactJS',
  'Proven experience with React',
  'with a strong focus on React',
  'experience with React.js',
  'Frontend Developer React',
  'Senior React Developer',
  'especializado en React',
  'experiencia con REACT',
  'specializing in React',
  'with a focus on React',
  'Expertise in React18',
  'Experiencia en React',
  'Proficiency in React',
  'expertise in React',
  'expert-level React',
  'features in React',
  'Full Stack React',
  'Dominio de React',
  'ReactJS Avanzado',
  'Front End React',
  'Senior ReactJS',
  'React Native',
].filter(Boolean);
