export const spainCitizenshipKeywords = [
  'Disponibilidad para ir dos veces al trimestre a Madrid',
  'Work must be performed exclusively from Spain',
  'Residir en España es un requisito Excluyente',
  'remote position for people located in Spain',
  'Imprescindible estar ubicado en España',
  'SOLO CANDIDATOS QUE VIVEN EN ESPAÑA',
  'Residencia en España imprescindible',
  'debe estar residiendo en Cataluña',
  'residir en MADRID o alrededores',
  'Indispensable vivir en España',
  'Permiso de trabajo en España',
  'Remote from any EU countries',
  'you must reside in Spain',
  'Full remote within Spain',
  'Residir en Galicia',
  'SPAIN BASED',
].filter(Boolean);
